---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0

jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.10

    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>

    environment:
      COVERAGE: true

    working_directory: ~/ldpath

    steps:
      - samvera/cached_checkout

      - run: 'sudo apt-get update'

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: "2"

      # - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      # - bundle_and_test:
      #     name: "ruby3-0"
      #     ruby_version: "3.0.0"
      - bundle_and_test:
          name: "ruby2-7"
          ruby_version: "2.7.5"
      - bundle_and_test:
          name: "ruby2-6"
          ruby_version: "2.6.9"
      - bundle_and_test:
          name: "ruby2-5"
          ruby_version: "2.5.9"
